[package]
name = "server"
version = "0.1.0"
edition = "2021"
authors = ["Giorgi Abuladze <itisabu@gmail.com>"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
